### ISSUE TITLE
Correction to front page display after the first merges were completed.

### ISSUE THREAD

**Issue by Kavishar29** [witseie-elen4010/2022-group-lab-003#15]
A bug was identified after the pull requests #13 and #14 were merged. We found that the board was below the key board.

## Acceptance criteria:
-board is above the keyboard
-the keyboard displays all the letters below the game board

**Comment by grandmaJ** [comment]
Comments:
- The board is correctly displayed above the keyboard
- The keyboard does correctly display all the letters below the game board
