### ISSUE TITLE
Web App deployment style formatting, as a user, the board and keyboard must be formatted and styles such that it is visible and attractive to the user when they play the game.

### ISSUE THREAD

**Issue by Kavishar29** [witseie-elen4010/2022-group-lab-003#22]
After deployment it was found that the web app was not styled, i.e. the .css file was not being read in the node app. this needs to be debugged for correct deployment of release 1 of the MULTI-Wordle web application game.

## Acceptance criteria:
- layout of the game front page is correct
- board is visible
- keyboard is visibale
- all features are styled according to the .css file
- user can play the game

**Comment by Kavishar29** [comment]
Correction is successful, the board and keyboard are clear to the user.
The styling is attractive and neat.
The game works on the website and can be played like wordle original.
The simple first version is good!

**Comment by faatimahomed** [comment]
Code debugged successfully.
User experience excellent for first version.
Features styled correctly.

**Comment by grandmaJ** [comment]
The layout has the game title, wordle board, keyboard, and instructions laid out correctly on the screen.
The user can play the game with the features that we have included.
Looks great!
