### ISSUE TITLE
As a player, I want to view the instructions of the game, so that I can understand how to play the game.

### ISSUE THREAD

**Issue by LutfiyaCharfaray** [witseie-elen4010/2022-group-lab-003#7]
## Estimated points

- Story points = 4

## Acceptance criteria

- Instructions are provided on how to play a basic version of this game.
- The instructions are clear and easy to understand.
- It has a neat layout.

#1

**Comment by Kavishar29** [comment]
The instruction page looks good. It provides a good brief into playing the game and it is structured well.

**Comment by LutfiyaCharfaray** [comment]
Thank you for your feedback! The instructions for the game will be updated as the functionality of the game improves.
